# See the documentation for more information:
# https://packit.dev/docs/configuration/

# Build targets can be found at:
# https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/

specfile_path: container-selinux.spec

jobs:
  - job: copr_build
    # Run on every PR
    trigger: pull_request
    owner: rhcontainerbot
    project: packit-builds
    enable_net: true
    actions:
      post-upstream-clone:
        - "curl -O https://src.fedoraproject.org/rpms/container-selinux/raw/rawhide/f/container-selinux.spec"
      fix-spec-file:
        - bash .packit.sh
