---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/container-selinux.spec
upstream_tag_template: v{version}

srpm_build_deps:
  - make

jobs:
  - job: copr_build
    trigger: pull_request
    notifications:
      failure_comment:
        message: "Ephemeral COPR build failed. @containers/packit-build please check."
    enable_net: true
    # container-selinux is noarch so we only need to test on one arch
    targets:
      - fedora-all
      - fedora-eln
      - centos-stream-9
      - centos-stream-8
    additional_repos:
      - "copr://rhcontainerbot/podman-next"

  # Run on commit to main branch
  - job: copr_build
    trigger: commit
    notifications:
      failure_comment:
        message: "podman-next COPR build failed. @containers/packit-build please check."
    branch: main
    owner: rhcontainerbot
    project: podman-next
    enable_net: true

  # All tests specified in the `/plans/` subdir
  # FIXME: uncomment e2e tests after disk space issues resolved on testing farm
  #- job: tests
  #  trigger: pull_request
  #  targets: *test_targets
  #  identifier: podman_e2e_test
  #  tmt_plan: "/plans/podman_e2e_test"

  - job: tests
    trigger: pull_request
    # arch assumed to be x86_64 by default.
    targets:
      - fedora-all
      - centos-stream-9
      - centos-stream-8
    identifier: podman_system_test
    tmt_plan: "/plans/podman_system_test"

  - job: propose_downstream
    trigger: release
    update_release: false
    dist_git_branches:
      - fedora-all

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched # rawhide updates are created automatically
