---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/container-selinux.spec
upstream_tag_template: v{version}

srpm_build_deps:
  - make

jobs:
  - job: copr_build
    trigger: pull_request
    notifications:
      failure_comment:
        message: "Ephemeral COPR build failed. @containers/packit-build please check."
    enable_net: true
    # container-selinux is noarch so we only need to test on one arch
    targets:
      - fedora-all
      - fedora-eln
      - epel-9
      - epel-8

  # Run on commit to main branch
  # Build targets managed in copr settings
  - job: copr_build
    trigger: commit
    notifications:
      failure_comment:
        message: "podman-next COPR build failed. @containers/packit-build please check."
    branch: main
    owner: rhcontainerbot
    project: podman-next
    enable_net: true

  # All tests specified in the `/plans/` subdir
  # Podman e2e tests for Fedora and CentOS Stream
  - job: tests
    trigger: pull_request
    notifications:
      failure_comment:
        message: "podman e2e tests failed. @containers/packit-build please check."
    targets: &pr_test_targets
      - fedora-all
      - epel-9
      - epel-8
    identifier: podman_e2e_test
    tmt_plan: "/plans/podman_e2e_test"

  # Podman system tests for Fedora and CentOS Stream
  - job: tests
    trigger: pull_request
    notifications:
      failure_comment:
        message: "podman system tests failed. @containers/packit-build please check."
    targets: *pr_test_targets
    identifier: podman_system_test
    tmt_plan: "/plans/podman_system_test"

  # Podman e2e tests for RHEL
  - job: tests
    trigger: pull_request
    use_internal_tf: true
    notifications:
      failure_comment:
        message: "podman e2e tests failed on RHEL. @containers/packit-build please check."
    targets: &pr_test_targets_rhel
      epel-9-x86_64:
        distros: [RHEL-9.4.0-Nightly,RHEL-9-Nightly]
      epel-8-x86_64:
        distros: [RHEL-8.9.0-Nightly,RHEL-8-Nightly]
    identifier: podman_e2e_test_internal
    tmt_plan: "/plans/podman_e2e_test"

  # Podman system tests for RHEL
  - job: tests
    trigger: pull_request
    use_internal_tf: true
    notifications:
      failure_comment:
        message: "podman system tests failed on RHEL. @containers/packit-build please check."
    targets: *pr_test_targets_rhel
    identifier: podman_system_test_internal
    tmt_plan: "/plans/podman_system_test"

  - job: propose_downstream
    trigger: release
    update_release: false
    dist_git_branches:
      - fedora-all

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched # rawhide updates are created automatically
