---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

# Build targets can be found at:
# https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/

specfile_path: container-selinux.spec


jobs:
  - &copr
    job: copr_build
    # Run on every PR
    trigger: pull_request
    owner: rhcontainerbot
    project: packit-playground
    enable_net: true
    # x86_64 is assumed by default
    # container-selinux is noarch so we only need to test on one arch
    targets: &test_targets
      - centos-stream+epel-next-9
      - centos-stream+epel-next-8
    srpm_build_deps:
      - make
      - rpkg
    actions:
      post-upstream-clone:
        - rpkg spec --outdir ./
      fix-spec-file:
        - bash .packit.sh

  - job: tests
    trigger: pull_request
    targets: *test_targets
    identifier: podman-e2e-test
    tmt_plan: "/plans/podman_e2e_test"

  - job: tests
    trigger: pull_request
    targets: *test_targets
    identifier: podman-system-test
    tmt_plan: "/plans/podman-system-test"
