---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

downstream_package_name: container-selinux
upstream_tag_template: v{version}

# Ref: https://packit.dev/docs/configuration#files_to_sync
files_to_sync:
  - src: rpm/gating.yaml
    dest: gating.yaml
  - src: plans/
    dest: plans/
    delete: true
  - src: test/
    dest: test/
    delete: true
  - src: .fmf/
    dest: .fmf/
    delete: true
  - .packit.yaml

packages:
  container-selinux-fedora:
    pkg_tool: fedpkg
    specfile_path: rpm/container-selinux.spec
  container-selinux-centos:
    pkg_tool: centpkg
    specfile_path: rpm/container-selinux.spec
  container-selinux-rhel:
    specfile_path: rpm/container-selinux.spec

srpm_build_deps:
  - make

jobs:
  - job: copr_build
    trigger: pull_request
    packages: [container-selinux-fedora]
    notifications: &copr_build_failure_notification
      failure_comment:
        message: "Ephemeral COPR build failed. @containers/packit-build please check."
    enable_net: true
    # container-selinux is noarch so we only need to test on one arch
    targets:
      - fedora-all
      - fedora-eln

  - job: copr_build
    trigger: pull_request
    packages: [container-selinux-centos]
    notifications: *copr_build_failure_notification
    enable_net: true
    targets:
      - centos-stream-9
      - centos-stream-10

  - job: copr_build
    trigger: pull_request
    packages: [container-selinux-rhel]
    notifications: *copr_build_failure_notification
    enable_net: true
    targets:
      - epel-9

  # Run on commit to main branch
  # Build targets managed in copr settings
  - job: copr_build
    trigger: commit
    packages: [container-selinux-fedora]
    notifications:
      failure_comment:
        message: "podman-next COPR build failed. @containers/packit-build please check."
    branch: main
    owner: rhcontainerbot
    project: podman-next
    enable_net: true

  # All tests specified in the `/plans/` subdir
  # Tests for Fedora
  - job: tests
    trigger: pull_request
    packages: [container-selinux-fedora]
    notifications: &test_failure_notification
      failure_comment:
        message: "Tests failed. @containers/packit-build please check."
    targets:
      - fedora-all

  # Tests for CentOS Stream
  - job: tests
    trigger: pull_request
    packages: [container-selinux-centos]
    notifications: *test_failure_notification
    targets:
      - centos-stream-9
      - centos-stream-10

  # Tests for RHEL
  - job: tests
    trigger: pull_request
    packages: [container-selinux-rhel]
    use_internal_tf: true
    notifications: *test_failure_notification
    targets:
      epel-9-x86_64:
        distros: [RHEL-9.4.0-Nightly,RHEL-9-Nightly]
      # Use centos-stream-10 until we have epel-10
      # TODO: Enable after RHEL-10 gets selinux-policy >= 40.13.1 which is
      # already on CentOS Stream 10.
      #centos-stream-10-x86_64:
        #  distros: [RHEL-10-Beta-Nightly]

  - job: propose_downstream
    trigger: release
    packages: [container-selinux-fedora]
    dist_git_branches:
      - fedora-all

  - job: propose_downstream
    trigger: release
    packages: [container-selinux-centos]
    dist_git_branches:
      - c10s

  - job: koji_build
    trigger: commit
    packages: [container-selinux-fedora]
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    packages: [container-selinux-fedora]
    dist_git_branches:
      - fedora-branched # rawhide updates are created automatically
